    drop table if exists movie_rating CASCADE;
    
    create table movie_rating (
       id bigint generated by default as identity,
        comment varchar(255),
        display_date date,
        imdbid varchar(255),
        rating double,
        primary key (id)
    )